=== grip-on-software/visualization-site/schema/prediction-site/configuration.json
{
    "$id": "https://gros.liacs.nl/schema/prediction-site/configuration.json",
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Prediction model configuration",
    "$ref": "#/$defs/configuration",
    "$defs": {
        "configuration": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "object",
                    "properties": {
                        "expression": {
                            "type": "string",
                            "description": "Expression of the label used as target output in the model."
                        },
                        "attributes": {
                            "type": "array",
                            "items": {
                                "description": "Name of a feature used as part of the expression for the target output label.",
                                "type": "string"
                            }
                        }
                    }
                },
                "assignments": {
                    "type": "object",
                    "patternProperties": {
                        ".*": {
                            "type": "object",
                            "properties": {
                                "expression": {
                                    "type": "string",
                                    "description": "Expression that is used to assign the generated feature."
                                },
                                "attributes": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "description": "Feature used in an assignment of another generated feature."
                                    }
                                }
                            }
                        }
                    }
                },
                "organizations": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "description": "Identifier of an organization whose projects and sprints are used in the data set."
                    }
                },
                "features": { 
                    "type": "array",
                    "items": {
                        "description": "Name of a feature used as input for the model.",
                        "type": "string"
                    }
                },
                "metadata": {
                    "type": "array",
                    "items": {
                        "description": "Name of a column of the data set used as metadata.",
                        "type": "string"
                    }
                },
                "model": {
                    "description": "Identifier of the model used.",
                    "type": "string"
                },
                "binary": {
                    "description": "Treshold at which a label value is converted to a binary classification, if provided.",
                    "oneOf": [
                        {"type": "number"},
                        {"type": "null"}
                    ]
                },
                "weighted": {
                    "description": "Whether input values were weighted to produce values at similar scales as input for the model.",
                    "type": "boolean"
                },
                "stratified": {
                    "description": "Whether the data set was resampled (some sample sprints provided more often) in order to create proportionally balanced subsets with normal distributions of the target label, when provided in batches to the model.",
                    "type": "boolean"
                },
                "min_date": {
                    "$ref": "#/$defs/datetime",
                    "description": "Earliest date and time of the sprints included in the data set that this model was trained/tested/validated on."
                },
                "max_date": {
                    "$ref": "#/$defs/datetime",
                    "description": "Latest date and time of the sprints included in the data set that this model was trained/tested/validated on."
                }
            }
        },
        "datetime": {
            "type": "string",
            "$comment": "Most implementations do not like having `\"format\": \"date-time\"` here as well as the `pattern`, because the former assumes a `T` separator. The pattern allows all four-digit years (1000-9999), all months with leading zeros (01-12), all days with leading zeros (01-31), even if this combination does not exist in that month or year. All two-digit hours, months and seconds with leading zeros are allowed.",
            "pattern": "^[1-9][0-9][0-9][0-9]-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]) [0-9][0-9]:[0-9][0-9]:[0-9][0-9]$"
        }
    }
}

=== grip-on-software/visualization-site/test/sample/prediction-site/data/configuration.json
{"assignments":{"number_of_devs":{"attributes":["number_of_vcs_devs","number_of_jira_devs","number_of_seats"],"expression":"number_of_devs=where(number_of_vcs_devs > 0, number_of_vcs_devs, mean(number_of_jira_devs, number_of_seats))"}},"weighted":true,"stratified":false,"features":["sprint_days","num_story_points","num_weighted_points","num_links","num_comments","avg_concurrent_progress","number_of_devs"],"binary":null,"model":"abe","label":{"expression":"round(done_story_points)","attributes":["done_story_points"]},"metadata":["project_id","sprint_id"]}
